version: 3
tasks:
  blog:dev:
    interactive: true
    cmds:
      - |+
        pushd apps/blog
        PORT=17001 pnpm run dev
        popd
  blog:build:
    interactive: false
    env:
      BLOGS_DIR:
        sh: "echo $PWD/blogs"
    cmds:
      - echo $BLOGS_DIR
      - |+
        pushd apps/blog
        npm run indexing
        popd

  til:dev:
    dir: ./apps/til
    interactive: true
    cmds:
      - npm run dev

  til:build:
    dir: ./apps/til
    vars:
      Image: docker.io/nxtcoder17/til.nxtcoder17.me
      Tag: v1.0.0
    cmds:
      - docker buildx build -t {{.Image}}:{{.Tag}} --build-context project=../.. .
      - docker push {{.Image}}:{{.Tag}} 

  til:deploy:
    vars:
      TilImage: docker.io/nxtcoder17/til.nxtcoder17.me:v1.0.0
    cmds:
      - nxt template parse --missing-key=error -f deploy/til-deployment.yml.tpl
        --set Name=til-web
        --set Namespace=nxtcoder17
        --set Image={{.TilImage}}
        --set ImagePullPolicy=Always
